import { CaseData } from "./types";

/** Full demo case pre-loaded with the exact structure, facts, parties, evidence methods, and filing strategy from the 2025 Zorbaz Pelican Lake Assault Project */
export const zorbazDemoCase: CaseData = {
  caseTitle: "Zorbaz Pelican Lake Unprovoked Chokehold Assault – Oct 17, 2025",
  victimName: "Jacob Albert Wagner",
  victimAddress: "50201 Fish Lake Way, Detroit Lakes, MN 56501",
  victimPhone: "651-600-1714",
  victimEmail: "pete.jake@gmail.com",
  
  incidentDate: "2025-10-17",
  incidentTime: "~8:00 PM",
  incidentLocation: "Zorbaz Restaurant / Pelican Lake",
  incidentAddress: "51709 County Highway 9, Pelican Rapids, MN",
  incidentDescription: "Victim seated calmly and passively at a table engaged in peaceful conversation. Assailant approached from behind without provocation, fighting words, or physical instigation and placed victim in a chokehold, dragged him to the ground, and inflicted a fingernail scratch to the neck. Victim lost air, possibly blacked out momentarily, lost a contact lens, and developed a severe full-body systemic rash the next day requiring Prednisone.",
  wasSeated: true,
  wasPassive: true,
  chokehold: true,
  lostAir: true,
  blackout: true,
  lostContact: true,
  neckScratch: true,
  
  assailantName: "Justin Tyler Studsrud",
  assailantDOB: "1977-05-14",
  assailantAddress: "24792 Tri Lakes Trail, Pelican Rapids, MN 56572",
  assailantCriminalHistory: "Extensive ND & MN history including prior Simple Assault (2002), Disorderly Conduct, Interfering with Public Officer, multiple alcohol-related, NSF checks, DUI, etc. (see full criminal history exhibits).",
  
  venueName: "Zorbaz of Pelican Lake, Inc. / Lake Life Hospitality Group",
  venueOwner: "Brett Allmaras (Operating Partner)",
  venueAddress: "1462 E Shore Dr, Detroit Lakes, MN 56501",
  bartenderName: "Amanda Jo Belz",
  bartenderAdmissions: "Admitted Justin was at the bar 'the whole time' watching the game; she directed the intoxicated Justin toward victim's table; 'definitely closer with Justin's family'; incident 'seemed provoked'.",
  ownerAdmissions: "'I'm definitely on Justin's side' and could 'understand why someone would want to hit [victim] in the head.' Imposed retaliatory ban on the victim while shielding the assailant.",
  overserving: true,
  directedToTable: true,
  retaliatoryBan: true,
  
  deputyName: "Deputy Aaron Will",
  agency: "Otter Tail County Sheriff's Office",
  bodycamIssues: "Intentionally failed to record three critical phone calls with victim (while recording mundane interactions). In those calls repeatedly called it 'just a dumb bar fight' and claimed victim's words provoked the assault. Stopped/turned off bodycam at Studsrud residence precisely when Justin began discussing drunken parties with West Fargo police officers. Speaker labels reversed in Amanda Belz interview transcript.",
  fabricatedQuotes: "Report falsely attributes 'What's it to you?' and 'So what if I did?' to victim. Victim only asked legitimate question 'What if I did?' and proactively stated he thought assailant believed he was insulting the mother-in-law.",
  unrecordedCalls: "Three critical unrecorded calls on 10/17 (10:35pm, 3m32s), 10/18 (3:39pm, 4m52s), 10/20 (4:19pm, 5m6s) where Deputy downplayed assault and asserted provocation.",
  witnessCollusion: "Failed to separate Justin, Leah Studsrud, and Jillene Beyer at residence. Allowed real-time collusion and story-shifting from denied 'cunt' slur to fabricated military-son death insult. At Zorbaz allowed biased Brett Allmaras and Amanda Belz to provide input while reviewing video.",
  selectiveEnforcement: "Requested PBT only from the victim (who approached with hands raised). Ignored Justin's bloodshot watery eyes and slurred speech. Charged victim with two counts of Disorderly Conduct while Justin received only light plea. Justin re-entered premises and continued ranting yet faced no additional charge of Offensive/Abusive Conduct that was filed against victim.",
  biasIndicators: "'I gotcha, bro', bro-hug, fist bumps with Justin. Reassured 'I'm not taking you into jail', pre-judged 'just a misdemeanor'. Framed chokehold as 'protection' of mother-in-law. Relayed unverified military-son rumor to Zorbaz staff as fact despite knowing video had no audio. Explicitly stated plan to 'go both ways' and charge both with disorderly even after acknowledging 'since you assaulted him'.",
  
  victimCaseNumber: "56-CR-25-2609",
  assailantCaseNumber: "56-CR-25-2598",
  victimCharges: "Disorderly Conduct (Brawling/Fighting) Minn. Stat. § 609.72 subd. 1(1); Disorderly Conduct (Offensive, Abusive, Obscene) § 609.72 subd. 1(3)",
  assailantCharges: "Assault-5th Deg-Inflict or Attempt Bodily Harm § 609.224.1(2) – Dismissed via plea 03/30/2026 without victim notification",
  assailantPleaDate: "2026-03-30",
  assailantPleaResult: "5th Degree Assault dismissed; pleaded to Disorderly Conduct with unsupervised probation up to 6 months + Anger Management Assessment completed",
  victimRightsViolation: true,
  noNotification: true,
  
  prosecutor1Name: "Jesse P. Oelfke",
  prosecutor1Role: "Assistant County Attorney – handled Studsrud plea (56-CR-25-2598)",
  prosecutor2Name: "Lindsey Broda",
  prosecutor2Role: "Assistant County Attorney – lead on Wagner case (56-CR-25-2609); opposed dismissal",
  
  injuries: [
    {
      description: "Chokehold: loss of air, possible momentary blackout, fingernail scratch to neck, lost contact lens",
      date: "2025-10-17",
      treatment: "Reported on bodycam immediately",
      provider: "Deputy Will bodycam + later urgent care",
      meds: "",
      ongoing: false,
    },
    {
      description: "Severe full-body systemic rash originating from neck scratch (allergic dermatitis secondary to trauma/scratch)",
      date: "2025-10-18",
      treatment: "Urgent Care visit Monday Oct 20, 2025 – diagnosed Allergic dermatitis due to other chemical product; prescribed Prednisone",
      provider: "Sanford Health – Detroit Lakes Family Medicine / Dr. Jamey Jessen, MD",
      meds: "Prednisone",
      ongoing: true,
    },
  ],
  
  evidence: [
    {
      id: "ev1",
      type: "surveillance",
      title: "Zorbaz Surveillance Video (no audio)",
      date: "2025-10-17",
      description: "Clearly shows victim seated calmly/passively when Studsrud approaches from behind and applies chokehold. No physical aggression or fighting words visible from victim.",
      keyQuotes: ["Victim remained seated and calm until attacked from behind."],
    },
    {
      id: "ev2",
      type: "bodycam",
      title: "Dep. Will Bodycam – Zorbaz 10/17/2025",
      date: "2025-10-17",
      description: "Victim approaches with hands raised, states 'it's all on camera', reports lost air / possible blackout / lost contact. Deputy requests PBT only from victim.",
      keyQuotes: ["I lost air", "might have blacked out a little bit", "It's all on camera"],
    },
    {
      id: "ev3",
      type: "bodycam",
      title: "Dep. Will Bodycam – Studsrud Residence 10/17/2025",
      date: "2025-10-17",
      description: "Failed separation of witnesses. Story shift from denied 'cunt' slur to military-son fabrication. Bro-hug, 'I gotcha bro', fist bumps. Bodycam stopped during West Fargo police parties discussion.",
      keyQuotes: ["I gotcha, bro", "I'm not taking you into jail", "just a misdemeanor", "Sticks and stones... protecting your mother-in-law"],
    },
    {
      id: "ev4",
      type: "bodycam",
      title: "Dep. Will Bodycam – Brett Allmaras & Amanda Belz 10/20/2025",
      date: "2025-10-20",
      description: "Brett: 'definitely on Justin's side' + understands wanting to hit victim. Amanda: directed intoxicated Justin to table, closer with family, 'seemed provoked'. Speaker labels reversed in transcript.",
      keyQuotes: ["I'm definitely on Justin's side", "understand why someone would want to hit [him] in the head", "definitely closer with that family"],
    },
    {
      id: "ev5",
      type: "medical",
      title: "Urgent Care Records + Prednisone Rx + Follow-up MyChart",
      date: "2025-10-20",
      description: "Sanford Health visit for derm problem. Dr. Jessen later confirmed scratch appearance and possible Neosporin reaction. Full-body rash started Oct 18.",
    },
    {
      id: "ev6",
      type: "report",
      title: "Deputy Will Investigation Report (fabricated quotes)",
      date: "2025-10-17",
      description: "Contains quotes never said by victim. Contradicted by bodycam.",
    },
    {
      id: "ev7",
      type: "other",
      title: "Studsrud Criminal Histories (ND + MN)",
      date: "2026-05",
      description: "Prior Simple Assault, Disorderly, Obstruct Officer, alcohol, financial crimes, etc.",
    },
    {
      id: "ev8",
      type: "email",
      title: "Oelfke email 04/07/2026 apologizing for no victim notification of plea",
      date: "2026-04-07",
      description: "Explicit admission of 611A violation.",
    },
  ],
  
  filings: [
    {
      id: "f1",
      type: "Civil Demand Letter",
      recipient: "Lake Life Hospitality / Zorbaz / Justin Studsrud",
      dateFiled: "2026-04-10",
      status: "sent",
      trackingNumber: "Certified Mail",
      nextAction: "Await response / insurance tender; 21-day demand window",
      notes: "$165,000 joint & several demand for battery, premises, Dram Shop § 340A.801, gross negligence",
    },
    {
      id: "f2",
      type: "POST Board Misconduct Complaint",
      recipient: "MN POST Board – Deputy Aaron Will",
      dateFiled: "2026-04-10",
      status: "sent",
      notes: "Fabrication, suppression, collusion, selective enforcement, bias, bodycam termination",
    },
    {
      id: "f3",
      type: "OLPR Ethical Complaint",
      recipient: "Office of Lawyers Professional Responsibility – Jesse Oelfke",
      dateFiled: "2026-04",
      status: "acknowledged",
      trackingNumber: "File No. 51626",
      notes: "611A violation + reliance on tainted investigation. Notice of Investigation issued 04/21/2026 to 7th District DEC",
    },
    {
      id: "f4",
      type: "OLPR Ethical Complaint",
      recipient: "OLPR – Lindsey Broda",
      dateFiled: "2026-04",
      status: "draft",
      notes: "Pursued retaliatory charges on tainted investigation; opposed dismissal",
    },
    {
      id: "f5",
      type: "Crime Victim Rights Act Complaint",
      recipient: "MN Crime Victim Justice Unit (Suzanne Elwell)",
      dateFiled: "2026-04-13",
      status: "acknowledged",
      notes: "No notification of plea negotiations/hearing/resolution of assault charge",
    },
    {
      id: "f6",
      type: "Human Rights Complaint",
      recipient: "MN Department of Human Rights",
      dateFiled: "2026-04",
      status: "sent",
      notes: "Discriminatory treatment / denial of equal protection in LE response",
    },
    {
      id: "f7",
      type: "Board Oversight Request",
      recipient: "Otter Tail County Board of Commissioners",
      dateFiled: "2026-04",
      status: "sent",
      notes: "Request exercise of oversight over Sheriff & County Attorney offices",
    },
    {
      id: "f8",
      type: "Letter to Court",
      recipient: "Hon. Judge Kevin Miller",
      dateFiled: "2026-04-11",
      status: "sent",
      notes: "Request formal recognition of 611A violation + vacate Studsrud plea",
    },
    {
      id: "f9",
      type: "Response to Cease-and-Desist",
      recipient: "Luke Heck / Vogel Law Firm (for Studsrud)",
      dateFiled: "2026-05-28",
      status: "sent",
      notes: "Point-by-point rejection; protected pre-litigation activity; consciousness of liability",
    },
  ],
  
  hearings: [
    {
      id: "h1",
      date: "2026-02-19",
      time: "",
      type: "Contested Omnibus / Evidentiary Hearing (PC challenge)",
      location: "Otter Tail County District Court, Fergus Falls",
      caseNumber: "56-CR-25-2609",
      notes: "Defense exhibits: bodycams + transcripts. State: report + surveillance.",
    },
    {
      id: "h2",
      date: "2026-07-09",
      time: "8:30 AM",
      type: "Jury Roll Call",
      location: "121 W. Junius Ave, Fergus Falls MN",
      caseNumber: "56-CR-25-2609",
      notes: "Original date – later rescheduled",
    },
    {
      id: "h3",
      date: "2026-07-21",
      time: "8:30 AM",
      type: "Jury Trial",
      location: "121 W. Junius Ave, Fergus Falls MN",
      caseNumber: "56-CR-25-2609",
      notes: "Original trial date – rescheduled to ~end Aug / Sept 1 2026",
    },
  ],
  
  demandAmount: 165000,
  demandDate: "2026-04-09",
  demandStatus: "sent – awaiting response",
  lastUpdated: new Date().toISOString(),
};
